#!/usr/bin/env bash
# Deploy-Skript für Studio Avelin Child Theme -> IONOS SFTP

REMOTE_HOST="access-5020051294.webspace-host.com"
REMOTE_USER="su433285"
REMOTE_PASS="Nes00235Nolen"
REMOTE_DIR="clickandbuilds/StudioAvelin/wp-content/themes/studio-avelin-child"
LOCAL_DIR="studio-avelin-child"

echo "🚀 Starte Deployment von ${LOCAL_DIR} zu IONOS (${REMOTE_DIR})..."

expect -c "
set timeout 60
spawn sftp -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST}
expect \"password:\"
send \"${REMOTE_PASS}\r\"
expect \"sftp>\"

send \"mkdir ${REMOTE_DIR}\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/templates\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/patterns\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/inc\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/parts\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/assets\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/assets/css\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/assets/js\r\"
expect \"sftp>\"
send \"mkdir ${REMOTE_DIR}/js\r\"
expect \"sftp>\"

send \"put ${LOCAL_DIR}/functions.php ${REMOTE_DIR}/functions.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/style.css ${REMOTE_DIR}/style.css\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/theme.json ${REMOTE_DIR}/theme.json\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/front-page.php ${REMOTE_DIR}/front-page.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/home.php ${REMOTE_DIR}/home.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/single.php ${REMOTE_DIR}/single.php\r\"
expect \"sftp>\"

send \"put ${LOCAL_DIR}/page-about-me.php ${REMOTE_DIR}/page-about-me.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-experiments.php ${REMOTE_DIR}/page-experiments.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/single-experiment.php ${REMOTE_DIR}/single-experiment.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-work.php ${REMOTE_DIR}/page-work.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-work-maaike-fiebus.php ${REMOTE_DIR}/page-work-maaike-fiebus.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-work-stan.php ${REMOTE_DIR}/page-work-stan.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-work-stat.php ${REMOTE_DIR}/page-work-stat.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-work-stau.php ${REMOTE_DIR}/page-work-stau.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-datenschutzerklaerung.php ${REMOTE_DIR}/page-datenschutzerklaerung.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-datenschutz.php ${REMOTE_DIR}/page-datenschutz.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/page-impressum.php ${REMOTE_DIR}/page-impressum.php\r\"
expect \"sftp>\"

send \"put ${LOCAL_DIR}/assets/css/home.css ${REMOTE_DIR}/assets/css/home.css\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/assets/css/sa-base.css ${REMOTE_DIR}/assets/css/sa-base.css\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/assets/css/journal.css ${REMOTE_DIR}/assets/css/journal.css\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/assets/css/pages.css ${REMOTE_DIR}/assets/css/pages.css\r\"
expect \"sftp>\"

send \"put ${LOCAL_DIR}/assets/js/home.js ${REMOTE_DIR}/assets/js/home.js\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/js/sa-work-slider.js ${REMOTE_DIR}/js/sa-work-slider.js\r\"
expect \"sftp>\"

send \"mkdir ${REMOTE_DIR}/parts\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/parts/sa-header.php ${REMOTE_DIR}/parts/sa-header.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/parts/sa-footer.php ${REMOTE_DIR}/parts/sa-footer.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/patterns/datenschutz.php ${REMOTE_DIR}/patterns/datenschutz.php\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/patterns/impressum.php ${REMOTE_DIR}/patterns/impressum.php\r\"
expect \"sftp>\"

send \"put ${LOCAL_DIR}/templates/page-datenschutz.html ${REMOTE_DIR}/templates/page-datenschutz.html\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/templates/page-datenschutzerklaerung.html ${REMOTE_DIR}/templates/page-datenschutzerklaerung.html\r\"
expect \"sftp>\"
send \"put ${LOCAL_DIR}/templates/page-impressum.html ${REMOTE_DIR}/templates/page-impressum.html\r\"
expect \"sftp>\"

send \"bye\r\"
interact
"

echo "✅ Deployment erfolgreich abgeschlossen!"
